config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#homepage'
  get 'about', to: 'pages#about'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true, length: { minimum: 3, maximum: 50}
	validates :description, presence: true, length: {minimum: 10, maximum: 300}
	

end

app/models/user.rb
class User < ActiveRecord::Base
	#Adding validations
	validates :username, 
	presence: true, 
	uniqueness: { case_sensitive: false}, 
	length: {minimum: 3, maximum: 25}

	#regex for email formatting
	VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

	validates :email,
	presence: true,
	length: {maximum: 105},
	uniqueness: { case_sensitive: false},
	format: { with: VALID_EMAIL_REGEX}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	#Causes these actions to call this method before running
	before_action :set_article, only: [:edit, :update, :destroy, :show] 

	def index #this will be found at articles itself
		#grab all articles
		@articles = Article.all
	end

	#these will be found at articles/NAME
	#IE articles/new

	def new
		@article = Article.new #goes to the article new webpage
	end

	def edit
	end

	def update
		if @article.update(article_params)
			flash[:success] = "Article was successfully updated"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	def create
		#render plain: params[:article].inspect #simple code to show what is recieved by the create action
		@article = Article.new(article_params)
		if @article.save #saves the artivle to the database
			flash[:success] = "Article was successfully created" #displays success message
			redirect_to article_path(@article) #calls the show action using the article as a parameter
		else
			flash[:notice] = "Article could not be created"
			render 'new' #go back to new article page
		end
	end

	def show


	end

	def destroy
		@article.destroy
		flash[:success] = "Article was successfully deleted"
		redirect_to articles_path
	end

	private
		def article_params #Private method used to whitelist paramerters used by the system
			params.require(:article).permit(:title, :description) #permits the title and desc
		end
		def set_article
			@article = Article.find(params[:id])
		end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def homepage
	
	end
	
	def about
	
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class="row">
	<div class='col-xs-12'>
		<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class="form-group">
				<div class="control-label col-sm-2">
				<%= f.label :title %>
				</div>
				<div class="col-sm-8">
				<%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
				<%= f.label :description %>
				</div>
				<div class="col-sm-8">
				<%= f.text_field :description, rows:10, class: "form-control", placeholder: "Body of article", autofocus: true %>
			</div>
			</div>
			<div class = "form-group">
				<div class="col-sm-offset-2 col-sm-10">
				<%= f.submit class: 'btn btn-primary btn-large'%>
				</div>
			</div>
		<% end %>
	
		<%= link_to "Articles listing", articles_path%>
	</div>
</div>

app/views/articles/edit.html.erb
<h1>Edit an existing article</h1>

<%= render 'form'%>

app/views/articles/index.html.erb
<h1>List of all articles</h1>
<%= link_to "Create new article", new_article_path%>
<table>
	<tr>
		<th>Title</th>
		<th>Description</th>
	</tr>

	<% @articles.each do |article| %>
	<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
	<div class="well well-lg">
	<div class="article-title">
		<%= link_to article.title, article_path(article)%>
	</div>
	<div class="article-body">
		<%= truncate(article.description, length: 100) %>
	</div>
	<div class="article-actions">
		<%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-success" %>
		<br>
		<%= link_to "Delete this article", 
			article_path(article), 
			method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, 
			class: "btn btn-xs btn-danger" %>
	</div>
	</div>
	</div>
	</div>
	<% end %>
</table>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render 'form'%>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
	<h4 class="center"><strong>Description</strong></h4>
<hr>
<%= simple_format(@article.description) %>
<div class="article-actions">
<%= link_to "All articles", articles_path, class: "btn btn-xs btn-primary" %>
<br>
<%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-success" %>
<br>
<%= link_to "Delete this article", 
	article_path(@article), 
	method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, 
	class: "btn btn-xs btn-danger" %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Made by Gregory Goldshteyn, Summer 2017
		</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
		</ul>
	</nav>
	</footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">

	<div class="col-xs-10 col-xs-offset-1">

	<% flash.each do |name, msg| %>

		<div class='alert alert-<%="#{name}" %>'><!--CHanges the alert typed based on the name of the arert-->

			<a href="#" class="close" data-dismiss="alert">×</a>

			<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>

		</div>

	<% end %>

	</div>

</div>

app/views/layouts/_navigation.html.erb
<!-- Basic code is from getbootstap.com search term navbar-->

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
	<!--<a class="navbar-brand" id="logo" href="#">Blog Website</a> This line is replaced by the proceeding line-->
	<%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
	<li><%= link_to "Articles", articles_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Article", new_article_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- This is the generic template for whole website -->
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    	<%= render 'layouts/navigation' %>
	<%= render 'layouts/messages' %>
	<!-- The yield is where the other pages are rendered -->
	<div class="container">
	<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

<%= link_to 'Home', root_path %>

app/views/pages/homepage.html.erb
<div class="center jumbotron"><!-- Having two classes means the object takes both classes attributes -->
<h1>My blog site</h1>
<%= link_to 'Sign up now', "#", class: "btn btn-primary btn-lg"%>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>

<div class="row">

	<div class="col-xs-8 col-xs-offset-2">

		<div class="panel panel-danger">

			<div class="panel-heading">

				<h2 class="panel-title">

				<%= pluralize(obj.errors.count, "error") %>

				prohibited this article from being saved:

				</h2>

				<div class="panel-body">

				<ul>

				<% obj.errors.full_messages.each do |msg| %>

				<li><%= msg %></li>

				<% end %>

				</ul>

				</div>

			</div>

		</div>

	</div>

</div>

<% end %>